apiVersion: v1
kind: Service
metadata:
  name: {{ include "__app__-web.fullname" . }}
  labels:
    {{- include "__app__-web.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.health.enabled }}
    - port: {{ .Values.health.port }}
      targetPort: http-health
      protocol: TCP
      name: http-health
    {{- end }}
  selector:
    app.kubernetes.io/component: server
    {{- include "__app__-web.selectorLabels" . | nindent 4 }}
