apiVersion: v2
name: __app__-db
description: databases for __app__

type: application

# chart version
version: '1.0.0'
# application version
appVersion: '1.0.0'

dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: '18.0.14'
    alias: postgres
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: '23.2.1'
    alias: redis
