nameOverride: ""
fullnameOverride: ""

migration:
  image:
    repository: ''
    pullPolicy: IfNotPresent
    tag: ''

  postgres:
    hostname: db-postgres
    port: 5432
    database: __app__
    username: postgres

postgres:
  auth:
    database: __app__
    username: __app__
    existingSecret: postgres-auth-secrets

  primary:
    extraEnvVarsSecret: postgres-primary-secrets
    extraEnvVars:
      - name: POSTGRESQL_PGAUDIT_LOG
        value: "all"

    initdb:
      user: postgres
      scripts:
        access.sql: |
          ALTER DEFAULT PRIVILEGES IN SCHEMA public
            GRANT ALL PRIVILEGES ON TABLES TO __app__;
          ALTER DEFAULT PRIVILEGES IN SCHEMA public
            GRANT ALL PRIVILEGES ON SEQUENCES TO __app__;

redis:
  architecture: standalone
  auth:
    existingSecret: redis-secrets
    existingSecretPasswordKey: redis-password
