apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "__app__-web.fullname" . }}
  labels:
    {{- include "__app__-web.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  PORT_HEALTH: {{ .Values.health.port | quote }}
  
  __app___API_HOST: {{ .Values.api.host }}
