apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - name: api
      port: 8443
      protocol: HTTPS
      hostname: api.__app__.localhost
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: api-__app__-api-tls
    - name: web
      port: 8443
      protocol: HTTPS
      hostname: app.__app__.localhost
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: web-__app__-web-tls
