POSTGRES_PASSWORD: ENC[AES256_GCM,data:+szRt+y9,iv:n5oGKw2dIQXHuZCHmBM/o8iengA1hTtQh6utuf95b8U=,tag:Omh6+YWk7frt+bMwoPMyMg==,type:str]
POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:IWo1ORKS,iv:H/2uCR7fG8GHYCmHW4jc8hpXEPPrXbAt+lTn2JahKOM=,tag:0EY8T0cAXkefq3GPNretrA==,type:str]
POSTGRES_REPLICATION_PASSWORD: ENC[AES256_GCM,data:nH0sGnDv,iv:/+ml296y6IZgaR72KtCdiwYSbng7vxoxz5CUIKVVjpA=,tag:uCFY9KsziCECa8B4dkXKGg==,type:str]
REDIS_PASSWORD: ENC[AES256_GCM,data:Sd7sEbUh,iv:fBtg7aLWCHNg8cFBBqWhQATHH5YPhNWzDLCTMmpkCsY=,tag:zg+bBQ5Z+5vUx9wb0Ayb4w==,type:str]
JWT_AUTH_SECRET: ENC[AES256_GCM,data:hqNAA0eG,iv:6Z2t2kzyTHKm3s03iD03zZ/QrjCNPRZkH1RyMPZIkKs=,tag:bdZmSfdzeFRhFCThPJh/KQ==,type:str]
API_TLS_CERT: ENC[AES256_GCM,data:upeaYgtP,iv:QsSFfgBOq8To+nVbxSbwoboVbfiRdXAS3eCDAf51jPc=,tag:UdUUVK9NloDg3vviwCnppw==,type:str]
API_TLS_KEY: ENC[AES256_GCM,data:qKEKi+6b,iv:Si6YN4dhkoTOvZB1IHrnOc/n2Evt7HUO8J/OXPCtYt8=,tag:bAa83nLaqW9Nyf95seX31w==,type:str]
WEB_TLS_CERT: ENC[AES256_GCM,data:0x8gOoHl,iv:rm6qc6qYNgWuGTu1Yp26uhQEUCx13zTixSjmm2OdtRs=,tag:dAaLgbTa/Wus4o+fbur42w==,type:str]
WEB_TLS_KEY: ENC[AES256_GCM,data:KFePj0HI,iv:smcct9s+kYS5h8A7Nokxv4K3n1O2x7yRVLXG2fcxW3Y=,tag:obUOb4WYwO87CYoO9sRSqg==,type:str]
sops:
  lastmodified: "2025-12-04T09:17:44Z"
  mac: ENC[AES256_GCM,data:D9RH+jZaFjbICr9fey0Ip46gk9KOE0FkDj8nFj04Z62bEL8pNBrzgSF8huocsEmPr5LyUk4kfSTMQu/NZekkby+1uHT/qjtWvauHe53sphAh+3kvONsXT8/GmeBsYdaDVpLYyZGDRMx8u4Cv742kVZwtNH2GMCq+6fT1VkL0gBw=,iv:1vCJdKyovKEtFYYC1rlm2iS8+E6ahOlJ2Dcwn8yyxwk=,tag:hSadChPvyaceK4gD54GkTg==,type:str]
  pgp:
    - created_at: "2025-10-14T14:48:45Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DibhzSPCfsQESAQdA5C+k5Je/SHznDj05B7ljImgzRMPDHUOYuKNcdSZrAiQw
        6RaVKJl23b6n3vsNuD0yEpENNl4I5xNesbVknCIL4OpNxTIEiozwTSN40tvkuOaC
        1GYBCQIQEdfQl6g6C1Pm//u5VwF7h5msvTzn1ipAd+MN7DdHxq8B/FokyvjG7OS1
        Uox79vz76DmdWuKgO1HOr0IXR8FcyRMr7iIPQfJgB2pD0Js6a6jzst5Qrc/9e1td
        nKhpjP6SrG0=
        =GGR/
        -----END PGP MESSAGE-----
      fp: 3205D67C84CD0480A16BBC7CF83561A568B69B43
  unencrypted_suffix: _unencrypted
  version: 3.11.0
