POSTGRES_PASSWORD: ENC[AES256_GCM,data:+szRt+y9,iv:n5oGKw2dIQXHuZCHmBM/o8iengA1hTtQh6utuf95b8U=,tag:Omh6+YWk7frt+bMwoPMyMg==,type:str]
POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:IWo1ORKS,iv:H/2uCR7fG8GHYCmHW4jc8hpXEPPrXbAt+lTn2JahKOM=,tag:0EY8T0cAXkefq3GPNretrA==,type:str]
POSTGRES_REPLICATION_PASSWORD: ENC[AES256_GCM,data:nH0sGnDv,iv:/+ml296y6IZgaR72KtCdiwYSbng7vxoxz5CUIKVVjpA=,tag:uCFY9KsziCECa8B4dkXKGg==,type:str]
REDIS_PASSWORD: ENC[AES256_GCM,data:Sd7sEbUh,iv:fBtg7aLWCHNg8cFBBqWhQATHH5YPhNWzDLCTMmpkCsY=,tag:zg+bBQ5Z+5vUx9wb0Ayb4w==,type:str]
API_TLS_CERT: ENC[AES256_GCM,data:upeaYgtP,iv:QsSFfgBOq8To+nVbxSbwoboVbfiRdXAS3eCDAf51jPc=,tag:UdUUVK9NloDg3vviwCnppw==,type:str]
API_TLS_KEY: ENC[AES256_GCM,data:qKEKi+6b,iv:Si6YN4dhkoTOvZB1IHrnOc/n2Evt7HUO8J/OXPCtYt8=,tag:bAa83nLaqW9Nyf95seX31w==,type:str]
WEB_TLS_CERT: ENC[AES256_GCM,data:0x8gOoHl,iv:rm6qc6qYNgWuGTu1Yp26uhQEUCx13zTixSjmm2OdtRs=,tag:dAaLgbTa/Wus4o+fbur42w==,type:str]
WEB_TLS_KEY: ENC[AES256_GCM,data:KFePj0HI,iv:smcct9s+kYS5h8A7Nokxv4K3n1O2x7yRVLXG2fcxW3Y=,tag:obUOb4WYwO87CYoO9sRSqg==,type:str]
sops:
  lastmodified: "2025-12-04T09:27:46Z"
  mac: ENC[AES256_GCM,data:xQkjil3deGgbXoiyH3L69C8EbneEC8Ux1WcrDxA+vy1dM3lgkOvfW0YA4gl35Q7H4voUo6kmzFBV4vSilNnBLvhIA4AgAtOxPduafer4AEqkMo6WNwESc64IxZLu3ZUUiou1svpB9y/CQCR46igCmcl8p+QvcxGeNitsYwR6xTQ=,iv:o1WHW+ev7o1+QooSd/xyMdnsIr51NeShgYByqU9pxIc=,tag:r4p4BgYK7YZ2rewfIj2rSg==,type:str]
  pgp:
    - created_at: "2025-10-14T14:48:45Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DibhzSPCfsQESAQdA5C+k5Je/SHznDj05B7ljImgzRMPDHUOYuKNcdSZrAiQw
        6RaVKJl23b6n3vsNuD0yEpENNl4I5xNesbVknCIL4OpNxTIEiozwTSN40tvkuOaC
        1GYBCQIQEdfQl6g6C1Pm//u5VwF7h5msvTzn1ipAd+MN7DdHxq8B/FokyvjG7OS1
        Uox79vz76DmdWuKgO1HOr0IXR8FcyRMr7iIPQfJgB2pD0Js6a6jzst5Qrc/9e1td
        nKhpjP6SrG0=
        =GGR/
        -----END PGP MESSAGE-----
      fp: 3205D67C84CD0480A16BBC7CF83561A568B69B43
  unencrypted_suffix: _unencrypted
  version: 3.11.0
