apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "__app__-api.fullname" . }}
  labels:
    {{- include "__app__-api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}

  WEB_ORIGIN: {{ .Values.web.origin }}
  
  POSTGRES_HOSTNAME: {{ .Values.postgres.hostname }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DATABASE: {{ .Values.postgres.database }}
  POSTGRES_USERNAME: {{ .Values.postgres.username }}

  REDIS_HOSTNAME: {{ .Values.redis.hostname }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_USERNAME: {{ .Values.redis.username }}
