apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ include "__app__-api.fullname" . }}-secrets"
  labels:
    {{- include "__app__-api.labels" . | nindent 4 }}
stringData:
  JWT_AUTH_SECRET: "ref+sops://k8s/secrets.yaml#/JWT_AUTH_SECRET"

  POSTGRES_PASSWORD: "ref+sops://k8s/secrets.yaml#/POSTGRES_PASSWORD"

  REDIS_PASSWORD: "ref+sops://k8s/secrets.yaml#/REDIS_PASSWORD"
