apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.auth.existingSecret }}
  labels:
    {{- include "__app__-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: "ref+sops://k8s/secrets.yaml#/REDIS_PASSWORD"
